### ISSUE TITLE
Where to put API key?

### ISSUE THREAD

**Issue by nordkite** [bahirul/yii2-short-url#1]
<pre>var_dump($json_decode_response);</pre>

Gives

<pre>
array(1) {
  ["error"]=>
  array(3) {
    ["errors"]=>
    array(1) {
      [0]=>
      array(4) {
        ["domain"]=>
        string(11) "usageLimits"
        ["reason"]=>
        string(23) "dailyLimitExceededUnreg"
        ["message"]=>
        string(76) "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
        ["extendedHelp"]=>
        string(36) "https://code.google.com/apis/console"
      }
    }
    ["code"]=>
    int(403)
    ["message"]=>
    string(76) "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
  }
}

</pre>

**Comment by nordkite** [comment]
I slightly modified your code. In 

<pre>shortUrl()</pre> added
<pre>
$apiKey = 'your-google-api-key';
and changed this line
curl_setopt($curl, CURLOPT_URL, 'https://www.googleapis.com/urlshortener/v1/url?key='.$apiKey);
</pre>

This way it worked.

**Comment by bahirul** [comment]
Thank you for reporting issue, i will make an update for next.
It will support composer install and API key.
